### ISSUE TITLE
No URLs to data files in anaconda-project.yml

### ISSUE THREAD

**Issue by dhruvbalwada** [pyviz-topics/examples#141]
The user guide (https://examples.pyviz.org/user_guide) has a note that reads: \
NOTE: If the notebook depends on data files, you will need to download them explicitly if you don’t use anaconda-project, by extracting the URLs defined in anaconda-project.yml and saving the file(s) to this directory.

I don't see any URLs in the yml file. If there is a single URL, would it not just be easier to place it in the markdown text in the example notebook itself? 

Here is the file I obtained from the datashader_dashboard example:
```
name: datashader_dashboard
description: Interactive dashboard for making Datashader plots from any dataset that
  has latitude and longitude
channels:
- conda-forge
- nodefaults
packages: &id001
- python=3.6
- notebook=5.7.8
- ipykernel=5.1.0
- nomkl
- anaconda-project=0.8.3
- colorcet=2.0.1
- datashader=0.7.0
- fastparquet=0.3.0
- holoviews=1.12.3
- hvplot=0.4.0
- intake=0.5.3
- intake-parquet=0.2.2
- panel=0.6.0
- param=1.9.1
- python-snappy=0.5.4
dependencies: *id001
commands:
  dashboard:
    unix: panel serve dashboard.ipynb
    supports_http_options: true
  census:
    unix: 'anaconda-project prepare --directory ../census

      DS_DATASET=census panel serve dashboard.ipynb

      '
    supports_http_options: true
  nyc_taxi:
    unix: 'anaconda-project prepare --directory ../nyc_taxi

      DS_DATASET=nyc_taxi panel serve dashboard.ipynb

      '
    supports_http_options: true
  opensky:
    unix: 'anaconda-project prepare --directory ../opensky

      DS_DATASET=opensky panel serve dashboard.ipynb

      '
    supports_http_options: true
  osm:
    unix: DS_DATASET=osm-1b panel serve dashboard.ipynb
    supports_http_options: true
  notebook:
    notebook: dashboard.ipynb
variables:
  DS_DATASET:
    description: Choose a dataset from nyc_taxi, osm-1b, census, opensky, nyc_taxi_small
    default: nyc_taxi_small
env_specs:
  default: {}
```
