### ISSUE TITLE
Declare live deployment targets

### ISSUE THREAD

**Issue by ablythed** [pyviz-topics/examples#171]
Right now, Jean-Luc is the only one who knows what should be deployed for which projects. Each anaconda-project.yml should declare what the live deployment targets are, e.g. by listing the command names under a user-defined field "live_deployments" with a dictionary command: endpoint.

**Comment by jlstevens** [comment]
An example might be `notebooks: attractors-notebooks`, `dashboard: attractors`.

**Comment by jlstevens** [comment]
It is worth mentioning is that we hope to have a consistent scheme. For project `FOO` it should always be this kind of mapping for notebooks and dashboards:

```
live_deployments: 
   notebooks: FOO-notebooks
   dashboard: FOO
```

At least when there are both types of deployment....

**Comment by jbednar** [comment]
"always" doesn't seem suitable in this case! Out of 39 projects, only four have a "notebooks" target, and only 13 have a "dashboard" target. More often there is a "notebook" target (33 projects).

**Comment by jlstevens** [comment]
I meant 'always' when there are both types of deployment in the same project: as you point out, that doesn't seem to be true for most of them...

**Comment by jbednar** [comment]
Sure, but even in that case we need to standardize between "notebooks" and "notebook".  

BTW, maybe we should invert this and instead put this info into the target itself? E.g.:

```
commands:
  dashboard:
    unix: panel serve *_panel.ipynb
    supports_http_options: true
    endpoint: attractors-dashboard
  notebooks:
    notebook: .
    endpoint: attractors-notebook
```

Not sure if that will cause any issues for anaconda-project...
